### ISSUE TITLE
Ghost latest version

### ISSUE THREAD

**Issue by mrneilypops** [SNathJr/ghost-on-heroku#10]
Hi,
How can I upgrade to Ghost v.2.25.4?
I see your repo is holding Ghost at v.2.21.0

Regards,

Neil

**Comment by SNathJr** [comment]
Hi @mrneilypops,

I tried updating ghost to the latest version, but since v.2.21.0 ghost has changed in such a manner it breaks this application while updating. I had investigated into the matter once and concluded it was because of the old version of adapters (S3 adapter, cloudinary adapter) ghost is having conflicts. I will look into it further in the near future and will update the ghost version.

Regards,
SNathJr

**Comment by mrneilypops** [comment]
Any update?
Ghost is now v.2.27.0

**Comment by SNathJr** [comment]
Updated to latest ghost :)

If you have any further queries, feel free to comment.
