### ISSUE TITLE
How to use an alternative theme (more specifically the paid membership ones: Lyra or Pico)

### ISSUE THREAD

**Issue by codechair** [SNathJr/ghost-on-heroku#28]
Hi,

Thanks for this work!

How to use an alternative theme with your package (more specifically the paid membership ones: Lyra or Pico)?
Links to them: 
https://github.com/TryGhost/Lyra
https://github.com/TryGhost/Pico

**Comment by SNathJr** [comment]
Hey @codechair 

This repo currently does not support paid themes (yet).

Regards,
SNathJr

**Comment by codechair** [comment]
Hi @SNathJr Thanks for your response.

Sorry I didn't make it clear. Those are not "paid themes", they are free themes by the Ghost team. But they allow publishers to turn ON the "members" feature and charge a subscription to their readers.

Given they are free and maintained by the Ghost team, I'd like to swap Casper to one of them (either Lyra or Pico).

So, back to my question, how could I do that with your package? How can I swap the theme?

**Comment by JaneJeon** [comment]
Hi, I helped with making the themes work on heroku and it's easy:
1. add your theme to `package.json` (for example, see here: https://github.com/SNathJr/ghost-on-heroku/blob/master/package.json#L19) note that we're pulling directly from github. It also might be a good idea to lock the theme versions because they frequently break :/
2. add that theme to the list of themes that need to be copied over to node_modules during installation: https://github.com/SNathJr/ghost-on-heroku/blob/master/bin/copy-themes.sh#L1
3. make a PR!

That's it :)

**Comment by SNathJr** [comment]
Hey @codechair 

This link: https://heroku.com/deploy?template=https://github.com/snathjr/ghost-on-heroku/tree/update-3-2-0 will deploy ghost-3.2.0 with lyra and pico. But, the subscribe now and login buttons for those themes won't work.

Cheers,
SNathJr

**Comment by codechair** [comment]
@SNathJr that is awesome! Could you expand why the subscribe now and login buttons won’t work? Whatever info you already have will help be debug. 

Thanks in advance

**Comment by JaneJeon** [comment]
I'm guessing it has to do with needing Stripe API tokens.

**Comment by SNathJr** [comment]
@JaneJeon @codechair 

I don't think this is a Stripe issue altogether. It might need stripe API tokens, but the theme does not seem to have /signup and /signin route generated. A simple test with pages simply named 'signup' and 'signin' revealed this. (you can check this out here: https://ghostlier.herokuapp.com/)

I think this could be because ghost does not have required backend implementations for them (maybe that's why you don't see releases for these themes just yet).

This is just what my take on the problem.

Cheers,
SNathJr

**Comment by codechair** [comment]
Will explore and revert should I get anywhere. Thanks both @SNathJr @JaneJeon

**Comment by codechair** [comment]
> Hey @codechair
> 
> This link: https://heroku.com/deploy?template=https://github.com/snathjr/ghost-on-heroku/tree/update-3-2-0 will deploy ghost-3.2.0 with lyra and pico. But, the subscribe now and login buttons for those themes won't work.
> 
> Cheers,
> SNathJr

Back to this, the link is dead, would you mind sharing a live one again?

Thanks a lot

**Comment by SNathJr** [comment]
@codechair 

That branch is now merged in master, so the deploy button of this repo should work just fine.

:)

**Comment by codechair** [comment]
@SNathJr HERO! thanks

**Comment by valentierra** [comment]
> @codechair Hi, I helped with making the themes work on heroku and it's easy:
> 
> 1. add your theme to `package.json` (for example, see here: https://github.com/SNathJr/ghost-on-heroku/blob/master/package.json#L19). Note that we're pulling directly from github so watch the package URL syntax. It also might be a good idea to lock the theme versions because they frequently break :/
> 2. add that theme to the list of themes that need to be copied over to node_modules during installation: https://github.com/SNathJr/ghost-on-heroku/blob/master/bin/copy-themes.sh#L1
> 3. make a PR!
> 
> That's it :)

I've been trying to include the following themes via package.json and copy-themes.sh:

```
"liebling": "github:eddiesigner/liebling",
 "simply": "github:godofredoninja/simply",
 "mapache": "github:godofredoninja/Mapache"
```

When installing Ghost for development:

```
warning mapache@3.1.1: The engine "ghost" appears to be invalid.
warning mapache@3.1.1: The engine "ghost-api" appears to be invalid.
...
... (*similar warnings for all themes*

warning "ghost > bookshelf@0.14.2" has incorrect peer dependency "knex@>=0.6.10 <0.15.0".
```

I have noticed some themes (attila, bleak, liebling, london, massively, the-shell, vapor) can not be activated because they have some CSS class and helpers errors, like they where taken from older versions. After I use the upload theme button to update those themes with the same version referred to in package.json, the theme begins to work.

As using the upload theme button for production on Heroku doesn't last, how could ensure the latest version of each theme is installed from package.json and copy-themes files?

**Comment by codechair** [comment]
@SNathJr and @JaneJeon 

> Will explore and revert should I get anywhere. Thanks both @SNathJr @JaneJeon

**Reverting as promised:**

I've made the "subscribe" and "log in" work

- Go to the Lyra repo: https://github.com/TryGhost/Lyra#instructions

- Download the code and upload `routes.yaml` into the admin of ghost under "labs" --> "beta features" --> "Routes" 

- Then "subscribe" and "log in" will work

Having said that, unsure if this will last (based on what I keep reading about stuff not lasting in ghost due to the "Ephimeral file system in Heroku" which I honestly have not understood yet). Care to clarify @SNathJr @JaneJeon ?
