### ISSUE TITLE
Redirect json file is missing after dyno restarts

### ISSUE THREAD

**Issue by keyuls** [SNathJr/ghost-on-heroku#43]
Ghost has option to upload redirects.json to handle redirection of old link to new link.
![image](https://user-images.githubusercontent.com/8844721/72853563-fd2ee700-3c6e-11ea-8b57-77643d1d0a32.png)

but after Heroku dyno restarts, the previously uploaded file is replaced with the empty file. 

How can I handle this?

**Comment by JaneJeon** [comment]
Sooooooo unfortunately you really can't trust Heroku to persist _anything_ in their filesystem, because after a restart it wipes _everything_ that is not in the "app" - namely, the source files and node_modules.

There really is no way around this :/
I had to use dirty hacks involving copying stuff from node_modules just to get the themes working, so it's really not possible to save an arbitrary JSON file, especially ones that get created AFTER the build step.

Your best bet is to fork this and add your custom redirect json file as _part of your repository source code_ so that Heroku knows not to yeet that file after a restart.
